// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAS3ZWxx1FEOQ0HOnIeOq4oKkQz3B5gdM4',
    appId: '1:645013067040:web:a22a55f79517dbeb163345',
    messagingSenderId: '645013067040',
    projectId: 'halokak-83cea',
    authDomain: 'halokak-83cea.firebaseapp.com',
    storageBucket: 'halokak-83cea.appspot.com',
    measurementId: 'G-M4YR1WL57M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFrryPaVwyOnp6EFGAjp98r4givnQoamI',
    appId: '1:645013067040:android:daca45901ae8be83163345',
    messagingSenderId: '645013067040',
    projectId: 'halokak-83cea',
    storageBucket: 'halokak-83cea.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCdYHp20mjgrcePznTLbKxRFsUrY53yt00',
    appId: '1:645013067040:ios:d7c040db6fb4d027163345',
    messagingSenderId: '645013067040',
    projectId: 'halokak-83cea',
    storageBucket: 'halokak-83cea.appspot.com',
    iosClientId: '645013067040-fmde67naqqnk6tid9rcbk3dsbjecfufk.apps.googleusercontent.com',
    iosBundleId: 'id.betalogika.halokakApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCdYHp20mjgrcePznTLbKxRFsUrY53yt00',
    appId: '1:645013067040:ios:d7c040db6fb4d027163345',
    messagingSenderId: '645013067040',
    projectId: 'halokak-83cea',
    storageBucket: 'halokak-83cea.appspot.com',
    iosClientId: '645013067040-fmde67naqqnk6tid9rcbk3dsbjecfufk.apps.googleusercontent.com',
    iosBundleId: 'id.betalogika.halokakApp',
  );
}
